### ISSUE TITLE
Baklava v2 stable release checklist

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#472]
- [x] Grace in main branch will be moved to a separate repository
- [x] Generated release notes will be tested before the merge
- [x] `next` and `main` branches should deploy storybook documentation to separate URLs. `next` branch can be also deployed to chromatic.
- [x] How chromatic tests will act on snapshots with `main` branch? What will be the baseline?
